trainer:
  max_epochs: 6
  accelerator: auto
  devices: 1
data:
  dataset_name: ETTh2
  seq_len: 336
  label_len: 336
  pred_len: 720
  variate: u
  target: OT
  frequency: h
model:
  model:
    class_path: models.Informer
    init_args:
      num_encoder_layers: 3
      num_decoder_layers: 2
      factor: 5
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse
