trainer:
  max_epochs: 6
  accelerator: auto
  devices: 1
data:
  dataset_name: ETTh2
  seq_len: 48
  label_len: 48
  pred_len: 24
  variate: m
  target: OT
  frequency: h
model:
  model:
    class_path: models.Informer
    init_args:
      factor: 5
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse
