trainer:
  max_epochs: 6
  accelerator: auto
  devices: 1
data:
  dataset_name: ETTm1
  seq_len: 672
  label_len: 96
  pred_len: 24
  variate: m
  target: OT
  frequency: t
model:
  model:
    class_path: models.Informer
    init_args:
      factor: 3
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse
